### PR TITLE
Fixes missing unlock calls

### PR DESCRIPTION
**Pull request by pvlieres**
**What happened?**
Sometimes, the server app didn't respond on endpoints like getting or creating a game. The HTTP requests for e.g. creating a new Game kept 'pending'. After a restart of the server, the endpoints work again.

**Potential fix:**
After digging into the code, it would make sense that `x.Unlock()` has not been called and the game is still locked. Thus, the requests cannot be handled properly. 

To make sure, the Lock is being removed, this PR defers the unlock call to the end of the function call where it's called independent of possible errors.

### CODE REVIEW

**Comment by philmtd** [comment]
Hey @pvlieres, thank you very much for your contribution!

Did you verify that these changes actually solve the problem you mentioned? Which version did you encounter these issues with? I fixed a similar-sounding problem in an earlier version.

While these changes look reasonable and ok I struggle to see where these errors should have previously occured between the calls to `lock` and `unlock`. All of the code between `lock` and `unlock` was either appending/deleting games from `games`, assigning variables or initializing structs. As the `gamesLock` is global across all games I didn't want to use `defer` because it would impact all parallel requests to the backend.

So if you encounter deadlocks in version 1.4.0 I am not sure whether these changes will fix them because I don't see critical code being executed between `lock` and `unlock`.

And if these changes actually do fix it, it might be because now the lock locks way more than just access to the `games` variable and then I'd like to trace the error to its root and fix the issue there.. :)

Do you have more information, logs or any way to test/reproduce this? If there actually is an issue I would of course like to resolve it asap. 🙃

**Comment by pvlieres** [comment]
Hey! Thanks for your reply. I'm with you that my proposed changes are not exactly perfect, it's rather been a best guess, that should break something. 

I run into the issue again and this time, I created a dump of the currently running go routines (`sudo kill -QUIT <pid>`). Please find this dump attached. 

It looks like there are several routines waiting for their locks. So, there seems to be some issue with those. It looks like it can be narrowed down to the use of blocking (unbuffered) channels in combination with locks. For instance, refer to the web socket disconnect handling.

 Unfortunately, I can't find the time to look deeper into that but I hope, this helps you somehow.

[fullhouse-go-routines.txt](https://github.com/philmtd/full-house/files/9910837/fullhouse-go-routines.txt)

**Comment by pvlieres** [comment]
Closing this for now as it seems that the root cause is not yet found.

**Comment by philmtd** [comment]
Thank you for your info! I will have a look on it and try to find the root cause as soon as I find some time!

**Pull request closed without merging**
